workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      groups:
        - react-native
    scripts:
      - npm install
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
