workflows:
  react-native-android:
    name: React Native Android Build
    environment:
      groups:
        - react-native
    scripts:
      - npm install
      - pwd                           # print current directory
      - ls -la                        # list files to confirm structure
      - cd android
      - ls -la                        # confirm gradlew exists
      - chmod +x ./android/gradlew
      - ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
